"""Move group id in to the student

Revision ID: 3b08d919e81a
Revises: b150f45660b3
Create Date: 2025-03-19 17:42:11.097157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b08d919e81a'
down_revision: Union[str, None] = 'b150f45660b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('groups_student_id_fkey', 'groups', type_='foreignkey')
    op.drop_column('groups', 'student_id')
    op.add_column('students', sa.Column('group_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'group_id')
    op.add_column('groups', sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('groups_student_id_fkey', 'groups', 'students', ['student_id'], ['id'])
    # ### end Alembic commands ###
