"""Add subject id in to the Grade

Revision ID: a3cd0c1947a4
Revises: 3b08d919e81a
Create Date: 2025-03-19 19:12:13.016237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3cd0c1947a4'
down_revision: Union[str, None] = '3b08d919e81a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grades', sa.Column('subject_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'grades', 'subjects', ['subject_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'grades', type_='foreignkey')
    op.drop_column('grades', 'subject_id')
    # ### end Alembic commands ###
